baseURL: https://blog.xiaoweigezzz.xyz/
timeZone: Asia/Shanghai
hasCJKLanguage: true
defaultContentLanguage: zh
defaultContentLanguageInSubdir: true
outputs:
  home:
    - HTML
    - calheatmap
    - RSS
    - Sitemap
outputFormats:
  calheatmap:
    mediaType: application/json
    baseName: cal-heatmap
    isPlainText: true
    permalinkable: true
