zh:
  contentDir: content
  languageCode: zh-CN
  languageName: 简体中文
  title: xiaoweige
  weight: 1
  defaultContentLanguageInSubdir: false
en:
  contentDir: content/en
  languageCode: en-US
  languageName: English
  title: xiaoweige
  weight: 2
