nav:
  - name: 议叙
    link: posts/
    target: _self
  - name: 卡片
    link: cards/
    target: _self
  - name: 书目
    link: library/
    target: _self
  - name: 假想
    link: fictions/
    target: _self
  - name: 自述
    link: about/
    target: _self
footerInternalLinks:
  - name: 林卷
    link: linkroll/
  - name: 赞助
    link: sponsor/
