author: xiaoweige
mainSections:
  - posts
  - fictions
  - library
favicon: /favicon.png
extraCSSFiles:
  - /pagefind/pagefind-ui.css
externalJSFIles:
  - /js/littlefoot.js
  - /pagefind/pagefind-ui.js
footerExternalLinks:
  - name: GitHub
    link: https://github.com/pawaovo/xiaoweige-blog
    icon: https://image.guhub.cn/uPic/2025/01/NqL5b5.png
# giscus 评论系统配置 - 需要您创建自己的 GitHub 仓库后配置
# giscus:
#   repo: yourusername/yourblog
#   repoId: YOUR_REPO_ID
#   category: General
#   categoryId: YOUR_CATEGORY_ID
#   mapping: og:title
#   strict: 1
#   reactionsEnabled: 0
#   emitMetadata: 0
#   inputPosition: top
#   theme: "https://yourdomain.xyz/css/giscus_noborder.css"
